### ISSUE TITLE
Bulk Import does not support JSON array document

### ISSUE THREAD

**Issue by kevinprotoss** [arangodb/arangojs#13]
Hi,

I found collection.import function does not support JSON array data. I think that's the reason of type parameter in the POST request

That's the error returned: 

```
Error: no JSON array found in second line
      at new ArangoError (/Invend/server_arango/node_modules/arangojs/lib/error.js:12:13)
      at Request._callback (/Invend/server_arango/node_modules/arangojs/lib/connection.js:65:25)
      at Request.self.callback (/Invend/server_arango/node_modules/request/request.js:373:22)
      at Request.EventEmitter.emit (events.js:110:17)
      at Request.<anonymous> (/Invend/server_arango/node_modules/request/request.js:1318:14)
      at Request.EventEmitter.emit (events.js:129:20)
      at IncomingMessage.<anonymous> (/Invend/server_arango/node_modules/request/request.js:1266:12)
      at IncomingMessage.EventEmitter.emit (events.js:129:20)
      at _stream_readable.js:898:16
      at process._tickCallback (node.js:343:11)
```

According to the documentation https://docs.arangodb.com/HttpBulkImports/ImportingSelfContained.html , the function should has something like the following for enabling parse of two types of JSON documents on the server side

https://github.com/arangodb/arangojs/blob/master/lib/collection.js#L168

```js
type: 'auto'
```

**Comment by jsteemann** [comment]
The following patch should fix this: https://gist.github.com/jsteemann/fd28801d787bc1ddf899
@pluma : can you review and include it if you're ok with it?

**Comment by pluma** [comment]
This isn't really a bug -- the `type` paramter can be specified using the `opts` argument:

```js
db.import(data, {type: 'array'}, callback);
```

But I think setting the default to `auto` is probably more convenient.

**Comment by pluma** [comment]
Okay, `type` now defaults to `"auto"` and I've documented the `type` parameter in case anyone wants to override it. Remind me to publish a new release ASAP.

**Comment by jsteemann** [comment]
:+1: Thanks

**Comment by kevinprotoss** [comment]
Hi, 

This patch worked for some time, but now it does not work again. See #21
