### ISSUE TITLE
ArangoDB 3.0.1 support

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [arangodb/arangojs#262]
```
{ ArangoError: database not found
    at new ArangoError (C:\localhost\ui-js\node_modules\arangojs\lib\error.js:30:15)
    at C:\localhost\ui-js\node_modules\arangojs\lib\connection.js:163:19
    at callback (C:\localhost\ui-js\node_modules\arangojs\lib\util\request.js:50:12)
    at IncomingMessage.<anonymous> (C:\localhost\ui-js\node_modules\arangojs\lib\util\request.js:58:11)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  errorNum: 1228,
  code: 404,
  response: 
  ....

```

**Comment by Simran-B** [comment]
What circumstances and what actions preceded this error?

**Comment by uMaxmaxmaximus** [comment]
I use 2.8, uninstall 2.8, install 3.0.1, run server, get this error in console

**Comment by uMaxmaxmaximus** [comment]
If i write this:

```javascript
(async function () {
	console.log(1)
	let db = arangojs()
	console.log(2)
	await db.createDatabase('ololo')
	console.log(3)
})()
```

in console i get this:
![image](https://cloud.githubusercontent.com/assets/19378179/16704345/85f6e574-457e-11e6-9efe-9883960575eb.png)


If i write this:
```javascript
(async function () {

	console.log(1)

	let db = arangojs({
		username: 'root',
		password: '',
		databaseName: 'ololo',
	})

	console.log(2)
	try {
		await db.createDatabase('ololo')
	} catch (e) {
		console.error(e)
	}
	
	console.log(3)

})();
```


in console i get:
```
1
2
{ ArangoError: database not found
    at new ArangoError (C:\localhost\ui-js\node_modules\arangojs\lib\error.js:30:15)
    at C:\localhost\ui-js\node_modules\arangojs\lib\connection.js:163:19
    at callback (C:\localhost\ui-js\node_modules\arangojs\lib\util\request.js:50:12)
    at IncomingMessage.<anonymous> (C:\localhost\ui-js\node_modules\arangojs\lib\util\request.js:58:11)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  errorNum: 1228,
  code: 404,
  response: 
   IncomingMessage {
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _events: { end: [Object], data: [Function] },
     _eventsCount: 2,
     _maxListeners: undefined,
     socket: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: 'localhost',
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        destroyed: false,
        _bytesDispatched: 181,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: null,
        read: [Function],
        _consuming: true },
     connection: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: 'localhost',
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        destroyed: false,
        _bytesDispatched: 181,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: null,
        read: [Function],
        _consuming: true },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers: 
      { server: 'ArangoDB',
        connection: 'Keep-Alive',
        'content-type': 'application/json; charset=utf-8',
        'content-length': '77' },
     rawHeaders: 
      [ 'Server',
        'ArangoDB',
        'Connection',
        'Keep-Alive',
        'Content-Type',
        'application/json; charset=utf-8',
        'Content-Length',
        '77' ],
     trailers: {},
     rawTrailers: [],
     upgrade: false,
     url: '',
     method: null,
     statusCode: 404,
     statusMessage: 'Not Found',
     client: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: 'localhost',
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        destroyed: false,
        _bytesDispatched: 181,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: null,
        read: [Function],
        _consuming: true },
     _consuming: true,
     _dumped: false,
     req: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedHeader: [Object],
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'POST /_db/ololo/_api/database HTTP/1.1\r\ncontent-type: application/json\r\ncontent-length: 16\r\nx-arango-version: 20300\r\nHost: localhost:8529\r\nConnection: keep-alive\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        method: 'POST',
        path: '/_db/ololo/_api/database',
        parser: null,
        res: [Circular] },
     read: [Function],
     body: 
      { error: true,
        errorMessage: 'database not found',
        code: 404,
        errorNum: 1228 },
     rawBody: '{"error":true,"errorMessage":"database not found","code":404,"errorNum":1228}' } }
3
```

**Comment by uMaxmaxmaximus** [comment]
this is work:

```javascript
	let host = 'localhost'
	let port = 8529
	let username = 'root'
	let password = ''


	let db = arangojs({
		url: `http://${username}:${password}@${host}:${port}`,
	})
```

**Comment by pluma** [comment]
I'm not sure I get what you're trying to do.

If you want to create a new database you have to create it from a connection to another database before you can use it. You can't use a database's API to create the database itself.

Try this:

```js
let db = arangojs({url: `http://root:@localhost:8529`}); // using "_system" database (default)
await db.createDatabase('otherdb');
db.useDatabase('otherdb');
// now the driver will use "otherdb" instead of "_system"
```

**Comment by dothebart** [comment]
@uMaxmaxmaximus any news on this? or can we close this?

**Comment by pluma** [comment]
I'm closing this as inactive. If you feel there's anything missing in my answer, feel free to re-open this issue with additional information.
