### ISSUE TITLE
Query is empty

### ISSUE THREAD

**Issue by kevinprotoss** [arangodb/arangojs#33]
Hi,

I updated the new version 3.7, but I found my code doesn't work any more. After deep inspect, I found the new utils/request can get the correct request body like the following:

```
Request Body: {"query":"LET nodes = (FOR node IN @@collection RETURN node), includes = (FOR node IN @@collection RETURN node) RETURN {nodes: nodes, includes: includes}","bindVars":{"@collection":"resources"}}
```

However the arangoDB returns an error, query is empty... I have no idea what's the reason.

```
{ [ArangoError: query is empty]\n  name: \'ArangoError\',\n  message: \'query is empty\',\n  errorNum: 1502,\n  code: 400,\n  stack: \'ArangoError: query is empty\\n    at new ArangoError (/Invend/nfserver/node_modules/arangojs/lib/error.js:10:13)\\n    at /Invend/nfserver/node_modules/arangojs/lib/connection.js:85:71\\n    at /Invend/nfserver/node_modules/arangojs/lib/util/once.js:7:15\\n    at IncomingMessage.<anonymous> (/Invend/nfserver/node_modules/arangojs/lib/util/request.js:23:9)\\n    at IncomingMessage.emit (events.js:129:20)\\n    at _stream_readable.js:908:16\\n    at process._tickDomainCallback (node.js:381:11)\',\n  isException: true,\n  status: 400 }
```

Meanwhile, I found the test case for query with Aqb module is missing. Maybe that's the reason.

Best regards,
Kevin

**Comment by kevinprotoss** [comment]
The complete error stack

```
{ [ArangoError: query is empty]
  message: 'query is empty',
  errorNum: 1502,
  code: 400,
  stack: 'ArangoError: query is empty\n    at new ArangoError (/Invend/nfserver/node_modules/arangojs/lib/error.js:10:13)\n    at /Invend/nfserver/node_modules/arangojs/lib/connection.js:85:71\n    at /Invend/nfserver/node_modules/arangojs/lib/util/once.js:7:15\n    at IncomingMessage.<anonymous> (/Invend/nfserver/node_modules/arangojs/lib/util/request.js:23:9)\n    at IncomingMessage.emit (events.js:129:20)\n    at _stream_readable.js:908:16\n    at process._tickDomainCallback (node.js:381:11)',
  response: 
   { _readableState: 
      { objectMode: false,
        highWaterMark: 16384,
        buffer: [],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null,
        resumeScheduled: false },
     readable: false,
     domain: null,
     _events: { end: [Object], data: [Function] },
     _maxListeners: undefined,
     socket: 
      { _connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: '127.0.0.1',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        bytesRead: 350,
        _bytesDispatched: 377,
        _pendingData: null,
        _pendingEncoding: '',
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     connection: 
      { _connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: '127.0.0.1',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        bytesRead: 350,
        _bytesDispatched: 377,
        _pendingData: null,
        _pendingEncoding: '',
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers: 
      { server: 'ArangoDB',
        connection: 'Keep-Alive',
        'content-type': 'application/json; charset=utf-8',
        'content-length': '73' },
     rawHeaders: 
      [ 'Server',
        'ArangoDB',
        'Connection',
        'Keep-Alive',
        'Content-Type',
        'application/json; charset=utf-8',
        'Content-Length',
        '73' ],
     trailers: {},
     rawTrailers: [],
     _pendings: [],
     _pendingIndex: 0,
     upgrade: false,
     url: '',
     method: null,
     statusCode: 400,
     statusMessage: 'Bad Request',
     client: 
      { _connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: '127.0.0.1',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        bytesRead: 350,
        _bytesDispatched: 377,
        _pendingData: null,
        _pendingEncoding: '',
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     _consuming: true,
     _dumped: false,
     req: 
      { domain: null,
        _events: [Object],
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        writable: true,
        _last: false,
        chunkedEncoding: true,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedHeader: {},
        _hasBody: true,
        _trailer: '',
        finished: true,
        _hangupClose: false,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'POST /_db/n-fuse/_api/cursor HTTP/1.1\r\ncontent-type: application/json\r\nx-arango-version: 20300\r\nHost: 127.0.0.1:8529\r\nConnection: keep-alive\r\nTransfer-Encoding: chunked\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        agent: [Object],
        socketPath: undefined,
        method: 'POST',
        path: '/_db/n-fuse/_api/cursor',
        parser: null,
        res: [Circular] },
     read: [Function],
     body: 
      { error: true,
        code: 400,
        errorNum: 1502,
        errorMessage: 'query is empty' },
     rawBody: '{"error":true,"code":400,"errorNum":1502,"errorMessage":"query is empty"}' } }
```

**Comment by jsteemann** [comment]
Confirmed with 3.7.0 and nodejs v0.10.25.
The reason is that the function in arangojs that assembles and sends the HTTP requests to the server does not set a `Content-Length` header for HTTP POST requests (and probably other methods). If the `Content-Length` header is omitted, http.request will default to using chunked transfer encoding, which is not supported. Setting a `Content-Length` HTTP header in lib/util/request.js will fix this:
```js
if (typeof body === 'string') {
  headers['Content-Length'] = body.length;
}
```
The docs for http.request are [here](https://nodejs.org/api/http.html#http_http_request_options_callback) and mention the special behavior of the `Content-Length` header:
> There are a few special headers that should be noted.
> ...
until the next request.
>     Sending a 'Content-length' header will disable the default chunked encoding.
> ...

Note: this behavior may be different depending on the node version?

**Comment by jsteemann** [comment]
@pluma: can you have a look at this? it seems to me that setting a `Content-Length` header in `lib/util/request.js` makes sense.

**Comment by pluma** [comment]
Yup. I wasn't aware that ArangoDB doesn't support chunked transfer-encoding. I'll add the content-length and release a patch release.

**Comment by pluma** [comment]
@kevinprotoss Can you give the current master a try and see if it fixes your problem?

**Comment by kevinprotoss** [comment]
@pluma Thx, it works now.

**Comment by bubnenkoff** [comment]
Is this issue fixed? I faced with same problem http://stackoverflow.com/questions/32420075/set-content-length-for-post-request-in-vibed
