### ISSUE TITLE
autoCreate collection sometimes fails

### ISSUE THREAD

**Issue by kevinprotoss** [arangodb/arangojs#35]
Hi,

I used database.collection function with `autoCreate` flag is true. Sometimes, I will get no error and a collection like this:

```
{ _connection: 
   { config: 
      { url: 'http://127.0.0.1:8529',
        databaseName: 'n-fuse',
        arangoVersion: 20300,
        agentOptions: [Object],
        headers: [Object] },
     _request: [Function: request] },
  _api: 
   { _connection: { config: [Object], _request: [Function: request] },
     _path: '_api',
     _headers: undefined } }
```

If I use this collection to call collection.import, I'll then got an error 

```
[ArangoError: 'collection' is missing, expecting /_api/import?collection=<identifier>]
  message: '\'collection\' is missing, expecting /_api/import?collection=<identifier>',
  errorNum: 1204,
  code: 400,
  stack: 'ArangoError: \'collection\' is missing, expecting /_api/import?collection=<identifier>\n    at new ArangoError (/Invend/nfserver/node_modules/arangojs/lib/error.js:10:13)\n    at /Invend/nfserver/node_modules/arangojs/lib/connection.js:90:71\n    at /Invend/nfserver/node_modules/arangojs/lib/util/once.js:7:15\n    at IncomingMessage.<anonymous> (/Invend/nfserver/node_modules/arangojs/lib/util/request.js:23:9)\n    at IncomingMessage.emit (events.js:129:20)\n    at _stream_readable.js:908:16\n    at process._tickDomainCallback (node.js:381:11)']
```

I believe generally the returned collection should like this:

```
{ _connection: 
   { config: 
      { url: 'http://127.0.0.1:8529',
        databaseName: 'n-fuse',
        arangoVersion: 20300,
        agentOptions: [Object],
        headers: [Object] },
     _request: [Function: request] },
  _api: 
   { _connection: { config: [Object], _request: [Function: request] },
     _path: '_api',
     _headers: undefined },
  id: '2903076799',
  name: 'organizations',
  waitForSync: false,
  isVolatile: false,
  isSystem: false,
  status: 3,
  type: 2 }
```

I'm not sure whether it's an issue of arangojs or arangoDB server. Please check with this case.

Best regards,
Kevin

**Comment by kevinprotoss** [comment]
p.s. the version of arangoDB is v2.5.4

Maybe it's the reason of new version of arangoDB, since I found some hang on requests for getting collection...

**Comment by kevinprotoss** [comment]
Well, I believe it's the reason of v2.5.4

I tried again with v2.5.3, no such case exists.

**Comment by jsteemann** [comment]
@pluma: can you check this? I strongly doubt this is server-related. `/_api/import` simply checks for a `collection` URL parameter and ever has since 1.0. Fetching collections shouldn't have changed either.

**Comment by pluma** [comment]
Can you check whether this problem (and #36, which I suspect to be related) persists in 3.7.1?

**Comment by kevinprotoss** [comment]
@pluma: I had tried again. I found both problems disappear now. Thx

**Comment by pluma** [comment]
You're welcome. Sorry for the inconvenience.
