### ISSUE TITLE
err ? callback(err) : callback(null, err)

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [arangodb/arangojs#365]
```javascript
await collection.createIndex(path, {
  type: 'skiplist',
  unique: true
})
```

```cmd
C:\Users\my\localhost\taxi\node_modules\arangojs\lib\collection.js:573
        return err ? callback(err) : callback(null, res.body);
                     ^

TypeError: callback is not a function
    at C:\Users\my\localhost\taxi\node_modules\arangojs\lib\collection.js:573:22
    at C:\Users\my\localhost\taxi\node_modules\arangojs\lib\connection.js:165:13
    at callback (C:\Users\my\localhost\taxi\node_modules\arangojs\lib\util\request.js:50:12)
    at IncomingMessage.<anonymous> (C:\Users\my\localhost\taxi\node_modules\arangojs\lib\util\request.js:58:11)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by pluma** [comment]
`createIndex` takes exactly one argument. if you pass two arguments, the second argument is assumed to be a node-style callback: https://github.com/arangodb/arangojs#collectioncreateindex

**Comment by pluma** [comment]
I'm closing this issue. If there's anything unclear about my explanation or if you have any follow-up questions, feel free to re-open the issue.
