### ISSUE TITLE
Error with useBasicAuth with the latest version

### ISSUE THREAD

**Issue by davidemiceli** [arangodb/arangojs#463]
Installing the latest version of arangojs I have this error:

```
/home/nodeapp/node_modules/arangojs/lib/util/btoa.js:8
  return Buffer.from(str).toString('base64');
                ^

TypeError: this is not a typed array.
    at Function.from (native)
    at exports.default (/home/nodeapp/node_modules/arangojs/lib/util/btoa.js:8:17)
    at new Connection (/home/nodeapp/node_modules/arangojs/lib/connection.js:78:76)
    at new Database (/home/nodeapp/node_modules/arangojs/lib/database.js:49:24)
    at module.exports (/home/nodeapp/node_modules/arangojs/lib/index.js:18:10)
    at Object.<anonymous> (/home/nodeapp/models/schemas.js:30:31)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```

with the following code:

```javascript
const db = require('arangojs')();

db.useBasicAuth(db_user, db_pwd);
db.useDatabase('testdatabase');
```
Before of update arangojs, it worked... why this problem?

**Comment by davidemiceli** [comment]
Sorry: I resolved.

It was because I had an old version of node (4.4.7), I tried with the last version (6.11) and it worked!
