### ISSUE TITLE
Saving collection throws 601 error on Ubuntu

### ISSUE THREAD

**Issue by RedDuckss** [arangodb/arangojs#491]
Recently switch over to Ubuntu 16.04 from Windows for redis support (and also because all my VPS' run Ubuntu) while developing, and found that my code no longer works due to a 601 error being thrown on saving. My whole script is too long to post here, but here is a snippet that throws the error:
```javascript
let ArangoDB = require('arangojs')();

ArangoDB.useBasicAuth('username', 'password');
ArangoDB.useDatabase('account_db');

let user_collection = ArangoDB.collection('users');

(async () => {
    await user_collection.save({
        test: 'test'
    });
    console.log('done');
})()
```
This throws the error:
```
(node:15748) UnhandledPromiseRejectionWarning: ArangoError: superfluous suffix, expecting /_api/document?collection=<identifier>
    at new ArangoError (/home/jonathan/Documents/Programming/NodeJS/defire_auth_server/node_modules/arangojs/lib/error.js:30:15)
    at /home/jonathan/Documents/Programming/NodeJS/defire_auth_server/node_modules/arangojs/lib/connection.js:204:21
    at callback (/home/jonathan/Documents/Programming/NodeJS/defire_auth_server/node_modules/arangojs/lib/util/request.node.js:52:9)
    at IncomingMessage.<anonymous> (/home/jonathan/Documents/Programming/NodeJS/defire_auth_server/node_modules/arangojs/lib/util/request.node.js:63:11)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```
Even using the example code found on this repo's README (https://github.com/arangodb/arangojs#documentcollectionsave) throws the error:
```javascript
let Database = require('arangojs');
const ArangoDB = new Database();
ArangoDB.useDatabase('account_db');
const collection = ArangoDB.collection('users');
const data = {some: 'data'};
const opts = {returnNew: true};
const doc = collection.save(data, opts)
```

The error `superfluous suffix` leads me to believe it is throwing a 601. I was not having this issue on Windows 10, only after switching to Ubuntu 16.04

**Comment by pluma** [comment]
Can you clarify which version of ArangoDB and which version of arangojs you are using?
