### ISSUE TITLE
How to replace a status in array ?

### ISSUE THREAD

**Issue by yuvanesh10** [arangodb/arangojs#518]
I have tried to modify a document by using data queries.
       `FOR u IN users
          FILTER u.status == "true"
           UPDATE u WITH { status: "inactive" } IN users`
This works fine for a normal structure. But when query is in a array form. This doesn't seems to replace or modify. How can I achieve this ?

this is my array

     `{
      "slave_state_datasets": [
        {
        "no": 0,
        "name": "abce",
        "status": true,
        "interrupt_time": 0.2,
        "timestamp": 1,
        "dataset_input": [
          {
          "data": 8,
          "ui16_u_u2": 1,
          "ui16_u_dip_min": 1,
          "ui16_u_swell_max": 1,
           }
        ]
      }
     ]
     }`

**Comment by jsteemann** [comment]
For the above data, the following should work:
```
FOR u IN users
    FILTER true IN u.slave_state_datasets[*].status
    LET updated = (
     FOR sub In u.slave_state_datasets
       RETURN MERGE(sub, { status: "inactive" })
   )   
  UPDATE u WITH { slave_state_datasets: updated } IN users
```

**Comment by yuvanesh10** [comment]
wow ..,amazing !! this works like a charm..! thank you so much  
isn't it like a subquery ? and there are no documentation regarding this  anywhere.

**Comment by Simran-B** [comment]
The part in parentheses is a subquery: `LET updates = ( ... )`

Subqueries as well as the individual high-level operations and functions are all documented. Are you missing examples how to update nested data structures like yours?

**Comment by yuvanesh10** [comment]
ja i mean...,the query examples to deal with arrays

**Comment by noahehall** [comment]
heres a sample error 

```js
pathServer:  thus far {
pathServer:   id: 'adult-literacy-and-high-school-equivalency-diploma-teachers',
pathServer:   itemId: 'base',
pathServer:   obj: { playerIds: [ 'nirv', 'a' ] },
pathServer:   prop: 'strategies'
pathServer: }
pathServer: 
pathServer: 
pathServer:  using this hsit base { playerIds: [ 'nirv', 'a' ] } strategies adult-literacy-and-high-school-equivalency-diploma-teachers
pathServer: 
pathServer:       data: {
pathServer:   "docKey": "adult-literacy-and-high-school-equivalency-diploma-teachers",
pathServer:   "collectionName": "Paths",
pathServer:   "itemId": "base",
pathServer:   "obj": {
pathServer:     "playerIds": [
pathServer:       "nirv",
pathServer:       "a"
pathServer:     ]
pathServer:   },
pathServer:   "prop": "strategies"
pathServer: } 
pathServer: 
pathServer: 
pathServer:       error executing Paths/undefined.
pathServer: 
pathServer:       query: {
pathServer:   "query": "\n          LET doc = DOCUMENT(@value0/@value1)\n          let itemId = @value2\n          let obj = @value3\n          let prop = @value4\n\n          let updated = (\n            FOR item in doc[prop]\n            FILTER item.id == itemId\n            return MERGE(item, obj)\n          )\n          UPDATE doc WITH { [prop]: updated} in @@value5\n          RETURN doc\n\n        ",
pathServer:   "bindVars": {
pathServer:     "value0": "Paths",
pathServer:     "value1": "adult-literacy-and-high-school-equivalency-diploma-teachers",
pathServer:     "value2": "base",
pathServer:     "value3": {
pathServer:       "playerIds": [
pathServer:         "nirv",
pathServer:         "a"
pathServer:       ]
pathServer:     },
pathServer:     "value4": "strategies",
pathServer:     "@value5": "Paths"
pathServer:   }
pathServer: } 
pathServer: 
pathServer: 
pathServer:       error: ArangoError: AQL: collection or array expected as operand to FOR loop; you provided a value of type 'null' (while executing)
pathServer:       
pathServer: (node:3049) UnhandledPromiseRejectionWarning: ArangoError: AQL: collection or array expected as operand to FOR loop; you provided a value of type 'null' (while executing)
pathServer:     at new ArangoError (/home/s/git/nirv/node_modules/arangojs/src/error.ts:76:17)
pathServer:     at Object.resolve (/home/s/git/nirv/node_modules/arangojs/src/connection.ts:378:20)
pathServer:     at callback (/home/s/git/nirv/node_modules/arangojs/src/connection.ts:220:16)
pathServer:     at IncomingMessage.<anonymous> (/home/s/git/nirv/node_modules/arangojs/src/util/request.node.ts:117:15)
pathServer:     at IncomingMessage.emit (events.js:224:7)
pathServer:     at IncomingMessage.EventEmitter.emit (domain.js:482:12)
pathServer:     at endReadableNT (_stream_readable.js:1206:12)
pathServer:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
pathServer: (node:3049) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
pathServer: (node:3049) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
pushServer: complete stack []


```

**Comment by noahehall** [comment]
im thinking the doc isnt being returned?
