### ISSUE TITLE
query(...) has bad error handling.

### ISSUE THREAD

**Issue by iyobo** [arangodb/arangojs#524]
See this...
```
var queryObj = // A bad query object with a typo

try {
            const cursor = await this.db.query(queryObj);
            const results = await cursor.all();
           
            return results; //returns as {} instead of throwing error
        } catch (e) {
            console.error('There was an issue finding items with the AQL query ', queryObj)
            throw e;
        }
```
The error never gets caught because I never see my console.error message. Instead what I see is this totally disconnected console.error in my logs:
```
ArangoError: AQL: collection not found: c (while parsing)
    at new ArangoError (/projects/opensource/jollofjs/packages/jollof-data-arangodb/node_modules/arangojs/lib/async/error.js:67:21)
    at Object.resolve (/projects/opensource/jollofjs/packages/jollof-data-arangodb/node_modules/arangojs/lib/async/connection.js:224:24)
    at _hosts.(anonymous function) (/projects/opensource/jollofjs/packages/jollof-data-arangodb/node_modules/arangojs/lib/async/connection.js:97:26)
    at IncomingMessage.res.on (/projects/opensource/jollofjs/packages/jollof-data-arangodb/node_modules/arangojs/lib/async/util/request.node.js:44:17)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
There is no trace of my source code in this error to know exactly where this error is coming from. 
This means the query functions in the module do not actually throw any ArangoErrors in such a way that is catchable by blocks up the stack.

query(...) returns an empty object even if an error happened and doesn't throw the ArangoError so one cannot even ascertain which query failed? 

This is a very bad approach to error handling. 
How have others been using this without having unstable apps?

**Comment by mpv1989** [comment]
Hi @iyobo ,

we implemented a test for your problem but we can not reproduce the described behavior with it. Is it possible that the posted stacktrace occurs in a different place?

If you are seeing an object as return value of `query()` or `cursor.all()` that usually indicates a missing `await`. Are you sure the code you posted is the code being executed?

best
Mark

**Comment by pluma** [comment]
Hi @iyobo 

can you please provide an example that reproduces the problem you described?

We have created a test case but can not reproduce the error you're seeing so there's nothing we can do right now without further information. I'm closing this issue now but feel free to reopen it if the problem persists.
