### ISSUE TITLE
"document not found" error thrown after a 504 (in a cluster setup)

### ISSUE THREAD

**Issue by uditha-atukorala** [arangodb/arangojs#628]
**ArangoDB:** v3.4.8
**arangojs:** v6.10.0

This is a bit of a weird one and I'll try to explain the best I can.

On the surface it all looks fine and the error stack looks like this:
```
ArangoError: document not found
    at new ArangoError (/opt/package/node_modules/arangojs/lib/async/error.js:71:21)
    at Object.resolve (/opt/package/node_modules/arangojs/lib/async/connection.js:247:32)
    at _hosts.(anonymous function) (/opt/package/node_modules/arangojs/lib/async/connection.js:131:26)
    at IncomingMessage.res.on (/opt/package/node_modules/arangojs/lib/async/util/request.node.js:78:21)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:466:23)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)"
```

The `ArangoError` object is absolutely huge and somewhere in it I could see a `504`. 
```
"StatusCodeError: 504 - \"<html>\\r\\n<head><title>504 Gateway Time-out</title></head>\\r\\n<body bgcolor=\\\"white\\\">\\r\\n<center><h1>504 Gateway Time-out</h1></center>\\r\\n</body>\\r\\n</html>\\r\\n\""
```

Also there's a 504 that bubbles up as an unhandled promise rejection (thrown by the `request` package). 

So it seems like arangojs isn't handling the 504 but returns a "document not found" error instead?

**Comment by pluma** [comment]
You'd have to inspect the network communication but the 504 message looks like it's from a reverse proxy like nginx or Apache, not from ArangoDB itself.

Since arangojs doesn't know anything about ArangoDB error types, the ArangoError you're seeing must at least partially be from ArangoDB somehow. Can you clarify what you mean by "the object is huge" and where exactly you see the 504 message?

Try running node with `--async-stack-traces` (this should be the default in latest Node 12) to figure out where the errors (and the unhandled rejection) originate. It's impossible to diagnose this based on the synchronous stack traces alone.

**Comment by pluma** [comment]
ArangoDB is at version 3.7 and this issue seems like it's related to a reverse proxy, not ArangoDB itself, and it doesn't seem to be related to arangojs itself. I'm closing this issue due to inactivity. Feel free to reopen the issue with additional information if the problem persists and you think it might be arangojs related.
