### ISSUE TITLE
executeTransaction - require as action function attribute

### ISSUE THREAD

**Issue by Tnifey** [arangodb/arangojs#636]
Hi, I've got improvement proposal.

**Problem:**
When using webpack/node. In executeTransaction, `require` tries to import not existing `@arango` package.
![image](https://user-images.githubusercontent.com/8442019/69826432-60723f00-1213-11ea-9a64-f820b6feaedf.png)
it fails with
```
(node:1859) UnhandledPromiseRejectionWarning: ArangoError: ReferenceError: __webpack_require__ is not defined
    at new ArangoError (/mnt/s/project/node_modules/arangojs/lib/async/error.js:71:21)
    at Object.resolve (/mnt/s/project/node_modules/arangojs/lib/async/connection.js:263:32)
    at callback (/mnt/s/project/node_modules/arangojs/lib/async/connection.js:129:26)
    at IncomingMessage.res.on (/mnt/s/project/node_modules/arangojs/lib/async/util/request.node.js:78:21)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Solution:**
If there was `require` function passed as argument, we can use it as internal arangodb/foxxx `require` inside action without error on client's side.
![image](https://user-images.githubusercontent.com/8442019/69826439-6b2cd400-1213-11ea-96ed-9f829881e422.png)

We can also do fake-passing as this function takes only `params` argument:
```ts
const action = function(params, require) {
  const { query } = require('@arangodb');
  return query`return true`;
}
db.executeTransaction(collections, action, options);

// inside executeTransation in src/database.ts
let actionString : string = String.raw`${action}`; // to ensure that is a string
const regex = /(?<=^\([\s\w\W]*|^function\s*\([\s\w\W]*)(\,\s*\brequire\b)(?=\s*\)\s*\=\>\s*\{|\s*\)\s*\{)/;
// this regex should work with this scenarios
// function (params, require) {}
// function ({ ids, ...params }, require) {}
// (params, require) => {} 
// ({ ids, ...params }, require) => {} // beware of using rest operator with !!webpack!!
// and also without require attribute
// (params) => {} 
// function (params) {}

actionString = actionString.trim().replace(regex, ''); // remove require from function attributes

  // ...request ...
    body: {
      action: actionString,
     // ...
  }
```
actionString produces `function (params) {...}` and it will use database's `require`

**Comment by pluma** [comment]
I think the cleaner solution is to write the function as normal and then turn it into a multi-line string by wrapping it in backticks.

Trying to mess with the parameter list before sending it to the server seems error-prone. We could change the actual implementation in ArangoDB to pass these globals (or at least `require`) as additional arguments if a workaround is really needed.

That said, have you looked into the streaming transactions API as an alternative?

https://github.com/arangodb/arangojs/blob/v6.12.0/docs/Drivers/JS/Reference/Database/Transactions.md#databasebegintransaction

**Comment by pluma** [comment]
I'm closing this issue due to inactivity as it's more of a general question than a bug.
