### ISSUE TITLE
Unhandled rejection ArangoError

### ISSUE THREAD

**Issue by Kurtas** [arangodb/arangojs#70]
I use promises in arango and I have problem with unhandled rejection, but I use catch. So, I realy don't understand what I'm  doing wrong. Maybe it's bug?

Here is my code, where I try to simulate error in query. 
```javascript
import Arango from 'arangojs';
import arangoConfig from './../../config/arango';
import Promise from 'bluebird';

const test = new Promise( (resolve,reject) => {
  reject(new Error('Promise rejected'));
})
//Test with classic promise
test.then( (msg) => {

}).catch( (err) => {
  console.log("Promise catched err: "+err);
})

const arDb = new Arango(arangoConfig);
//Empty query for simulation
arDb.query('').then( (msg) => {
    console.log(msg);
}).catch((err) => {
    console.log('Arrango catched Error: '+err );
});
```

Here is output:
```
Promise catched err: Error: Promise rejected
Arrango catched Error: ArangoError: query is empty (while parsing)
Unhandled rejection ArangoError: query is empty (while parsing)
    at new ArangoError (/home/node/discovery/node_modules/arangojs/lib/error.js:10:13)
    at /home/node/discovery/node_modules/arangojs/lib/connection.js:91:71
    at /home/node/discovery/node_modules/arangojs/lib/util/request.js:81:12
    at /home/node/discovery/node_modules/arangojs/lib/util/once.js:7:15
    at IncomingMessage.<anonymous> (/home/node/discovery/node_modules/arangojs/lib/util/request.js:89:11)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
```

**Comment by pluma** [comment]
I thought we had extinguished all of these.

The root cause is that promises were sometimes discarded because arangojs uses callbacks internally but some of the internal APIs *also* return promises. I'll look into this next week.

**Comment by pluma** [comment]
The driver will no longer return promises if a callback was passed, which should fix this problem.
