### ISSUE TITLE
GeneratedAqlQuery from aql-backticks returns "bind parameter 'value1' was not declared in the query"

### ISSUE THREAD

**Issue by oliverlockwood** [arangodb/arangojs#706]
On latest arangojs (7.2.0)

The code:
```
        const myQuery = aql`
            FOR edge IN ${arangoEdgeCollection}
            FILTER edge._from == '${edgeToSave._from}' AND edge.next == -1
            RETURN edge`;
        console.log(`Query: ${myQuery.query}`);
        console.log(`Query: ${JSON.stringify(myQuery.bindVars)}`);

        const response = await db.query(myQuery);
```

returns the following logs:
```
Query:
            FOR edge IN @@value0
            FILTER edge._from == '@value1' AND edge.next == -1
            RETURN edge
Query: {"@value0":"collection_item_edge_4","value1":"collection_4/596527a7-ed00-4a8c-bbd7-8b94371925f6"}
```

and throws the following error:
```
ArangoError: AQL: bind parameter 'value1' was not declared in the query (while parsing)
    at new ArangoError (/Users/oliverlockwood/work/flex-collection-service/Service/node_modules/arangojs/error.js:115:21)
    at Object.resolve (/Users/oliverlockwood/work/flex-collection-service/Service/node_modules/arangojs/connection.js:406:32)
    at callback (/Users/oliverlockwood/work/flex-collection-service/Service/node_modules/arangojs/connection.js:191:26)
    at IncomingMessage.<anonymous> (/Users/oliverlockwood/work/flex-collection-service/Service/node_modules/arangojs/lib/request.node.js:108:21)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  response: IncomingMessage {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: true,
      ended: true,
      endEmitted: true,
      reading: false,
      sync: true,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      emitClose: true,
      autoDestroy: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: true,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: false
    },
    readable: false,
    _events: [Object: null prototype] { end: [Array], data: [Function] },
    _eventsCount: 2,
    _maxListeners: undefined,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: true,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: null,
      timeout: 0,
      [Symbol(asyncId)]: -1,
      [Symbol(kHandle)]: [TCP],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    connection: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: true,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: null,
      timeout: 0,
      [Symbol(asyncId)]: -1,
      [Symbol(kHandle)]: [TCP],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    httpVersionMajor: 1,
    httpVersionMinor: 1,
    httpVersion: '1.1',
    complete: true,
    headers: {
      'x-content-type-options': 'nosniff',
      server: 'ArangoDB',
      connection: 'Keep-Alive',
      'content-type': 'application/json; charset=utf-8',
      'content-length': '133'
    },
    rawHeaders: [
      'X-Content-Type-Options',
      'nosniff',
      'Server',
      'ArangoDB',
      'Connection',
      'Keep-Alive',
      'Content-Type',
      'application/json; charset=utf-8',
      'Content-Length',
      '133'
    ],
    trailers: {},
    rawTrailers: [],
    aborted: false,
    upgrade: false,
    url: '',
    method: null,
    statusCode: 400,
    statusMessage: 'Bad Request',
    client: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: true,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: null,
      timeout: 0,
      [Symbol(asyncId)]: -1,
      [Symbol(kHandle)]: [TCP],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    _consuming: false,
    _dumped: false,
    req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      connection: [Socket],
      _header: 'POST /_db/flex-collection/_api/cursor HTTP/1.1\\r\
' +
        'authorization: Basic cm9vdDpwYXNzd29yZA==\\r\
' +
        'content-type: application/json\\r\
' +
        'x-arango-version: 30400\\r\
' +
        'content-length: 270\\r\
' +
        'Host: 192.168.0.20:8529\\r\
' +
        'Connection: keep-alive\\r\
' +
        '\\r\
',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      insecureHTTPParser: undefined,
      path: '/_db/flex-collection/_api/cursor',
      _ended: true,
      res: [Circular],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: true,
      host: '192.168.0.20',
      protocol: 'http:',
      onSocket: [Function],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      connection: [Socket],
      _header: 'POST /_db/flex-collection/_api/cursor HTTP/1.1\\r\
' +
        'authorization: Basic cm9vdDpwYXNzd29yZA==\\r\
' +
        'content-type: application/json\\r\
' +
        'x-arango-version: 30400\\r\
' +
        'content-length: 270\\r\
' +
        'Host: 192.168.0.20:8529\\r\
' +
        'Connection: keep-alive\\r\
' +
        '\\r\
',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      insecureHTTPParser: undefined,
      path: '/_db/flex-collection/_api/cursor',
      _ended: true,
      res: [Circular],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: true,
      host: '192.168.0.20',
      protocol: 'http:',
      onSocket: [Function],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    body: {
      code: 400,
      error: true,
      errorMessage: \"AQL: bind parameter 'value1' was not declared in the query (while parsing)\",
      errorNum: 1552
    },
    arangojsHostId: 0,
    [Symbol(kCapture)]: false
  },
  errorNum: 1552,
  code: 400
}"
```

Interestingly, another query variant which has three bind parameters resolves the first two but fails in the same way regarding  the third (i.e. `value2`).

This bug is such that I'm having to work around by using `aql.literal()` all over the shop, which is a pity (and obviously less secure).

Please let me know if I can provide any useful diagnostics to help investigate this issue.

**Comment by robross0606** [comment]
Have you tried not surrounding your `@value1` with quotes?  

```js
const myQuery = aql`
            FOR edge IN ${arangoEdgeCollection}
            FILTER edge._from == ${edgeToSave._from} AND edge.next == -1
            RETURN edge`;
```

My understanding was bind values would automatically generate those based on datatype of the bound value.

**Comment by pluma** [comment]
Hi @oliverlockwood,

@robross0606 is correct. When using the aql template tag, you don't need to provide the quotes yourself.

When using the template tag, arangojs will transmit both the query string (containing the generated bindVars names) and the bindVars mapping (containing the values). It doesn't actually inline the values.

**Comment by pluma** [comment]
I'm closing this question due to inactivity. Please check the community slack if you need further assistance: https://slack.arangodb.com
