### ISSUE TITLE
Attempting to update a document while using _rev property causes conflict

### ISSUE THREAD

**Issue by robross0606** [arangodb/arangojs#707]
This unit test fails:
```js

  it.only('Transaction stepping with updates causes conflict', async () => {
    const testCount = 10

    const db = arangoService.getInstance()
    const collection = await db.createCollection('test')
    const collectionData = await collection.get()
    expect(collectionData.type).toBe(CollectionType.DOCUMENT_COLLECTION)

    // Create documents
    const created = []
    for (let i = 0; i < testCount; i++) {
      created.push(await collection.save({ test: 'update-failure', count: 1 }, { returnNew: true }))
    }
    expect(created).toBeArrayOfObjects()
    expect(created).toBeArrayOfSize(10)

    // Now try to update them
    const updated = []
    for (const doc of created) {
      updated.push(
        await collection.update(
          doc._id,
          { _rev: doc._rev, updated: true },
          { returnOld: true, returnNew: true, keepNull: false, ignoreRevs: false }
        )
      )
    }
    expect(updated).toBeArrayOfObjects()
    expect(updated).toBeArrayOfSize(10)
  })
```

The error is:
```
    ArangoError: conflict

      at new ArangoError (node_modules/src/error.ts:143:17)
      at Object.resolve (node_modules/src/connection.ts:900:20)
      at callback (node_modules/src/connection.ts:628:16)
```

If `ignoreRevs` is set to `true` or the `_rev` property is not provided on the document content, the test passes.

**Comment by robross0606** [comment]
I have also tried with a single document update which also fails with the same error:
```js
  it.only('Document update with revision checking causes conflict', async () => {
    const db = arangoService.getInstance()
    const collection = await db.createCollection('test')
    const collectionData = await collection.get()
    expect(collectionData.type).toBe(CollectionType.DOCUMENT_COLLECTION)

    // Create documents
    const created = await collection.save({ test: 'update-failure' }, { returnNew: true })
    expect(created).toBeNonEmptyObject()
    expect(created._id).toBeNonEmptyString()
    expect(created._rev).toBeNonEmptyString()
    expect(created.new.test).toBe('update-failure')
    expect(created.new.updated).toBeFalsy()

    // Now try to update them
    const updated = await collection.update(
      created._id,
      { _rev: created._rev, updated: true },
      { returnOld: true, returnNew: true, mergeObjects: true, ignoreRevs: false }
    )
    expect(updated).toBeNonEmptyObject()
    expect(updated._id).toBe(created._id)
    expect(updated._rev).not.toBe(created._rev)
    expect(updated.new.test).toBe(created.new.test)
    expect(updated.new.updated).toBeTruthy()
  })
```
Failure:
```
    ArangoError: conflict

      at new ArangoError (node_modules/src/error.ts:143:17)
      at Object.resolve (node_modules/src/connection.ts:900:20)
      at callback (node_modules/src/connection.ts:628:16)
      at IncomingMessage.<anonymous> (node_modules/src/lib/request.node.ts:165:15)
```

**Comment by robross0606** [comment]
With the old driver where `revision` was passed in as an `option`, this resulted in an HTTP API header value:

```if-match: _bkexiY----```

However, with the new API, there is no `if-match` header value.  The value is passed in as a `_rev` in the body and this fails for some reason even though the HTTP API docs read for all the world like this should succeed:

> If the If-Match header is specified and the revision of the document in the database is unequal to the given revision, the precondition is violated.
> 
> If If-Match is not given and ignoreRevs is false and there is a _rev attribute in the body and its value does not match the revision of the document in the database, the precondition is violated.

**Comment by robross0606** [comment]
I think the documentation on HTTP API is incorrect, or at least misleading.  I tried this directly from the REST "Try It" feature on the Support page of the web UI and it fails in a similar manner.  If using the `If-Match` header it works fine.  If using a `_rev` stored in the body of the input, it fails:
![image](https://user-images.githubusercontent.com/2965467/102276060-4c6baf00-3ef4-11eb-9042-0e068c282d77.png)

**Comment by pluma** [comment]
Looks like the HTTP API docs are incorrect or misleading. It's probably easiest to restore the `if-match` behavior of v6, though I think the new option should be called `ifMatch` rather than `rev`.

**Comment by robross0606** [comment]
My issue with calling it `ifMatch` is you're intentionally breaking backward compatibility with previous versions of your library.  Putting back `rev` would make it backward compatible.

**Comment by robross0606** [comment]
FYI, underlying Arango bug (arangodb/arangodb#13232) is confirmed.

**Comment by Simran-B** [comment]
The server-side issue is fixed in 3.6.12 and 3.7.7, but it may still be desirable to have a driver-side workaround for earlier versions.

**Comment by robross0606** [comment]
@Simran-B, trying to plan for our own features. Any idea if/when a "driver-side workaround for earlier versions" might be implemented?

**Comment by robross0606** [comment]
@Simran-B I'm still confused about the outcome here.  I'm testing with Arango 3.7.7 and ArangoJS 7.4.0 and still seeing this not work.  I have `ignoreRevs: false` in the options and have tried multiple ways based on the documentation to confirm that it checks revisions properly:
- Putting `revision` in the update body
- Putting `_rev` in the update body
- Putting `revision` in the options like the old version

Now what I'm seeing is that it completely ignores the passing in revision when it is incorrect and updates the data anyway.  What is the correct way to use this such that it will actually validate the revision for both expected success _and_ failure?

**Comment by robross0606** [comment]
@Simran-B, I'm trying to figure out if this change now makes the ArangoJS 7.x driver incompatible with older servers.  This would appear to be the case as attempting to put `_rev` in the input with `ignoreRevs: false` against a 3.6.5 server breaks with the new structure.  Is there some way to use the 7.x line `update()` call with revision checks that is compatible with both 3.6.x and 3.7.x servers?

**Comment by robross0606** [comment]
@Simran-B, looks like this only fails on servers earlier than 3.6.12 so that may well be what you mean by:

> The server-side issue is fixed in 3.6.12 and 3.7.7, but it may still be desirable to have a driver-side workaround for earlier versions.

I wasn't expecting it to fail outright on earlier versions now.

**Comment by robross0606** [comment]
@Simran-B here are some wireshark captures of the update HTTP PATCH calls to compare responses from a 3.7.9 and 3.6.5 server.
[3.7.9 success.pcapng.log](https://github.com/arangodb/arangojs/files/6386126/3.7.9.success.pcapng.log)
[3.6.12 success.pcapng.log](https://github.com/arangodb/arangojs/files/6386128/3.6.12.success.pcapng.log)
[3.6.5 failure.pcapng.log](https://github.com/arangodb/arangojs/files/6386127/3.6.5.failure.pcapng.log)
The driver is clearly doing the same thing every time.  But the earlier versions of the server do not like the changes.

**Comment by robross0606** [comment]
@Simran-B, just noticed workaround hinted at in https://github.com/arangodb/arangodb/issues/13232#issuecomment-764728178.  Adding the `_key` to the input _does_ indeed appear to make calls cross-compatible with old and new versions.
