### ISSUE TITLE
Error: Socket hang up while db.query

### ISSUE THREAD

**Issue by mahesth** [arangodb/arangojs#723]
Hi, 

We have recently upgraded our arangodb to 3.6 and we are getting **ECONNRESET** error while running a query on specific collection. 

`error { Error: socket hang up
    at createHangUpError (_http_client.js:323:15)
    at Socket.socketOnEnd (_http_client.js:426:23)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  code: 'ECONNRESET'`

While executing the query manually in the query editor the query seems to ran fine without any issues. 

and we are getting this error only if the query execution time exceeds ~50 seconds. 

we get the ECONNRESET error in the code and strangely the **ArangoDB UI also logs out.** 

There were no **major page faults** happened and not much CPU hike also registered. 

_Need help on if any config change required in the code or in collections._

**Comment by pluma** [comment]
If the ArangoDB UI also logs out, this doesn't sound like it's caused by arangojs and rather ArangoDB itself reacting strangely to something you did. Can you clarify what exactly the query was doing?

Also note that by default he ArangoDB UI's query editor limits the number of results whereas arangojs does not impose such a limit by default, so if you were performing a query that would return a lot of results, that might explain the difference in behavior.

**Comment by mahesth** [comment]
Hi Pluma, 
Thanks for your answer. 

The query was just reading documents from various collections which has updated within the given timestamps. We did not retrieve full result but only the _key . 

we have used functions like , UNIQUE, FLATTEN, UNION_DISNTICT in the query. 

however, we have the same query running in ArangoDB 3.2 and no issues there. 

For the query editor, i had applied no limits on the query result.
