### ISSUE TITLE
outEdges and inEdges not working

### ISSUE THREAD

**Issue by robross0606** [arangodb/arangojs#802]
`edgeCollection.outEdges()` and `edgeCollection.inEdges()` no longer appear to be functional after upgrading from 7.8.0 to 8.6.0.  Making a call such as `await edgeCollection.outEdges('notLinks/test1')` results in this error stack:
```
    TypeError: Cannot read properties of undefined (reading 'allowDirtyRead')
      at Collection._edges (node_modules/src/collection.ts:3914:13)
      at Collection.outEdges (node_modules/src/collection.ts:3934:17)
      at Object.outEdges (src/__tests__/arango-service.test.js:506:39)
```

**Comment by robross0606** [comment]
The problem is definitely on `collection.ts`.

```js
    _edges(selector, options, direction) {
        const { allowDirtyRead = undefined } = options;
        return this._db.request({
            path: `/_api/edges/${encodeURIComponent(this._name)}`,
            allowDirtyRead,
            qs: {
                direction,
                vertex: (0, documents_1._documentHandle)(selector, this._name, false),
            },
        });
    }
    edges(vertex, options) {
        return this._edges(vertex, options);
    }
    inEdges(vertex, options) {
        return this._edges(vertex, options, "in");
    }
    outEdges(vertex, options) {
        return this._edges(vertex, options, "out");
    }
```

None of these functions has a default for `options` so it breaks `_edges` because `options` is undefined.
